server:
  servlet:
    context-path: /jobbuilder/v1
  port: 9090
logging:
  level:
    liquibase: TRACE
spring:
  application:
    name: job-builder-v1
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/jobbuilder?currentSchema=job
    username: postgres
    password: docker
  liquibase:
    enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
